<div align=center>

# Лабораторная работа № 7

</div>

Программирование алгоритмов определения max и min значений массивов

Необходиммые импорты

In [1]:
import numpy as np

12. Найти среднее арифметическое элементов массива, составленного из
максимальных элементов каждого столбца действительной матрицы
размера 10×15

In [18]:
matrix = np.random.randint(1, 100, size=(10, 15))

max_elements = []
for j in range(matrix.shape[1]):
    max_element = matrix[0, j]
    for i in range(1, matrix.shape[0]):  
        if matrix[i, j] > max_element:
            max_element = matrix[i, j]
    max_elements.append(max_element)

max_elements_array = np.array([max_elements] * 10)

average = np.mean(max_elements_array)

print(f"Среднее арифметическое максимальных элементов каждого столбца: {round(average, 2)}")

[[82 99 91 98 93 93 99 65 90 96 90 96 99 85 97]
 [82 99 91 98 93 93 99 65 90 96 90 96 99 85 97]
 [82 99 91 98 93 93 99 65 90 96 90 96 99 85 97]
 [82 99 91 98 93 93 99 65 90 96 90 96 99 85 97]
 [82 99 91 98 93 93 99 65 90 96 90 96 99 85 97]
 [82 99 91 98 93 93 99 65 90 96 90 96 99 85 97]
 [82 99 91 98 93 93 99 65 90 96 90 96 99 85 97]
 [82 99 91 98 93 93 99 65 90 96 90 96 99 85 97]
 [82 99 91 98 93 93 99 65 90 96 90 96 99 85 97]
 [82 99 91 98 93 93 99 65 90 96 90 96 99 85 97]]


Генерируем матрицу 10×15 из слусайных чисел. Циклом проходим по каждому столбцу, а вложенным циклом проходим по каждой строке в этом столбце и добавляем в список `max_elements`. Создаем массив `max_elements_array` в котором каждая строка состоит из элемнтов списка `max_elements`. Используя функцию `mean` находим находим среднее арифметическое всех элементов в массиве и выводим результат.

